"""empty message

Revision ID: d22ab8e0217f
Revises: 2e56fa40d5a5
Create Date: 2019-07-07 13:47:18.334992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22ab8e0217f'
down_revision = '2e56fa40d5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('isDelete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'isDelete')
    # ### end Alembic commands ###
